#dubbo:
#  application:
#    name: user-service-provider
#  registry:
#    address: 127.0.0.1:2181
#    protocol: zookeeper
#  protocol:
#    name: dubbo
#    port: 20881
#  monitor:
#    protocol: registry
#server:
#  port: 8081
